### PR TITLE
support serialization of more types

### PR DESCRIPTION
**Pull request by danielnorberg**

### CODE REVIEW

**Comment by honnix** [comment]
👍 . But maybe some description. The code looks a bit magical. Does that `PackageRegistrar` register everything?

**Comment by danielnorberg** [comment]
@honnix I'm not sure I wanted to merge this into that PR just yet

**Comment by honnix** [comment]
err... shall we revert?

**Comment by honnix** [comment]
nvm, it went to another PR which is still open.

**Pull request merged**
