### PR TITLE
Fail the task if `memoizer.store` fails.

### PR DESCRIPTION
**Pull request by honnix**
A new PR to fix commit mess of #44

### CODE REVIEW

**Comment by honnix** [comment]
@rouzwawi I closed #44 as my repo was in a very weird state.

**Comment by fabriziodemaria** [comment]
@honnix are your concerns about deadlock still valid in this new PR?

**Comment by honnix** [comment]
No. This is a much better solution. Basically constructing a new `Value`.

**Comment by fabriziodemaria** [comment]
I see, nice! Let's update the JavaDocs with the new behaviour of `store`.

We should also improve the printed logs in case of errors to make clear which Task failed publishing.

**Comment by honnix** [comment]
There is no new behaviour of `store`. We might want to make it explicitly declare throwing a checked exception, or in Javadoc make it clear what if the implementation throws `RuntimeException`.

**Comment by honnix** [comment]
In terms of logging, we are actually printing task id. E.g.
```
11:04:47.229 flo-worker-0                 | WARN | FloRunner  |> streamCount1(2016-10-01T00)#f5f57287 Failed
java.lang.RuntimeException: forced failure
...
```

**Comment by fabriziodemaria** [comment]
👍

**Pull request merged**
