### PR TITLE
remove unused value memoization code

### PR DESCRIPTION
**Pull request by danielnorberg**
# Hey, I just made a Pull Request!

## Description
Remove unused memoization code.

## Motivation and Context
This code is not used anywhere.

## Checklist for PR author(s)

- [x] Changes are covered by unit test
- [x] All tests pass
- [x] Code coverage check passes
- [ ] Error handling is tested
- [ ] Errors are handled at the appropriate layer
- [ ] Errors that cannot be handled where they occur are propagated
- [ ] Relevant documentation updated
- [ ] This PR has NO breaking change to public API
- [ ] This PR has breaking change to public API and it is documented

## Checklist for PR reviewer(s)

- [ ] This PR has been incorporated in release note for the coming version
- [x] Risky changes introduced by this PR have been all considered

### CODE REVIEW

**Comment by honnix** [comment]
I think this code was used to dedup tasks and also used by HadesContext internally. Not anymore? Would `ongoing.computeIfAbsent` achieve the same purpose of deduplication?

**Comment by honnix** [comment]
OK I guess not used anymore. I need to refresh my memory.

**Comment by honnix** [comment]
@rouzwawi PTAL I guess it was designed in this way for a purpose (that might not be valid anymore).

**Comment by rouzwawi** [comment]
I believe the initial design was meant to allowing types that were used as return types from a task, to override a task if there was a way to externally determine if the value was already present.

But it turned out it wasn't the best choice to put that on the task type and instead it was moved to `TaskContextStrict` and `OverridingContext`. So even thought this is a breaking change, it should be fine for a new major release.

**Comment by bergman** [comment]
Nice find and cleanup @danielnorberg !

**Comment by honnix** [comment]
👍 to make it official

**Pull request merged**
