### PR TITLE
flo-scala: support for scala 2.12 and 2.11

### LINKED ISSUE #55: flo-scala_2.12 ?
It would be nice to have a release of `flo-scala` both for scala 2.11 and scala 2.12. That means having support for cross builds.

### PR DESCRIPTION
**Pull request by labianchin**
Fixes #55 

- Bump to scala 2.11.11
- Include support for 2.12

### CODE REVIEW

**Comment by bergman** [comment]
Thanks a lot Luis! Will have a look when I get back to Stockholm.

**Comment by bergman** [comment]
I've tried this out locally for a bit and there seems to be some problem with the symlink from `flo-scala_2.12/src -> flo-scala_2.11/src`. The result is an empty jar for 2.12 while the 2.11 works fine. I tried copying the `src` directory instead of symlinking and then it worked (at least compiled, didn't test more).

Also, could you rebase on master so the version is `0.2.3-SNAPSHOT`?

**Comment by bergman** [comment]
Making these changes to 2.12 pom.xml and deleting the symlink seems to work:

```diff
  <build>
+   <sourceDirectory>../flo-scala_2.11/src/main/java</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>3.2.2</version>
        <executions>
          <execution>
            <id>add-generated-sources</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
+             <sourceDir>${project.build.directory}/generated-sources/annotations</sourceDir>
            </configuration>
          </execution>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <sourceDir>../flo-scala_2.11/src/main/scala</sourceDir>
          <scalaVersion>${scala.version}</scalaVersion>
          <sendJavaToScalac>false</sendJavaToScalac>
          <addScalacArgs>-Xexperimental</addScalacArgs>
        </configuration>
      </plugin>

```

**Comment by labianchin** [comment]
I think I forgot to properly validate.

On latest change I did:
- Rebased and adjusted to `0.2.3-SNAPSHOT` version
- Moved the `src` to `flo-scala_2.12` 
- Configured `sourceDir`/`sourceDirectory` on `flo-scala_2.11/pom.xml`. That seems better than symlinks.

```sh
ls -lh flo-scala_*/target/*.jar
-rw-r--r-- 1 labianchin 359K Apr 10 19:36 flo-scala_2.11/target/flo-scala_2.11-0.2.3-SNAPSHOT.jar
-rw-r--r-- 1 labianchin 288K Apr 10 19:36 flo-scala_2.12/target/flo-scala_2.12-0.2.3-SNAPSHOT.jar
```

Please have another look.

**Comment by bergman** [comment]
Thanks so much for this @labianchin 😄

**Pull request merged**
